### ISSUE TITLE
Docker container does get terminated if options passed

### ISSUE THREAD

**Issue by nivida** [cgewecke/geth-dev-assistant#11]
Hey! 

As long as I run ``geth-dev-assistant`` without any options passed does it work as expected and the container will run in the background. But as soon as I add options as for example ``gasLimit`` does it start to get flaky. 
The startup process of the docker container does finish and ``geth`` does get started as expected also the mining towards the specified ``gasLimit`` is running but the container will get stoped after (checked with ``docker ps -a``).  

osx: Mojave (10.14.5 (18F203))
docker: 2.1.0.5

**Comment by nivida** [comment]
screenshot:
<img width="1920" alt="Bildschirmfoto 2019-11-27 um 13 55 22" src="https://user-images.githubusercontent.com/1699173/69725070-99c88300-111d-11ea-98c5-6be8cb9af536.png">

script command:
```"start:geth": "geth-dev-assistant --gasLimit 9000000"```

**Comment by nivida** [comment]
I've checked this closer. On a fresh start of docker and start of the geth container does it work the first time as expected. But on a second start after stopping the geth container is the container not existing in the background.

**Comment by cgewecke** [comment]
@nivida Ah strange, are you stopping the client by running?
```
docker stop geth-client
```
 Or a different way?

**Comment by nivida** [comment]
@cgewecke Yes, I'm closing the container with ``docker stop geth-client``. 

> In the E2E scripts at Web3 that command is called at the end to close the client down. And repeated use with flags there seems like its working...

Hmm.. strange 🤔

**Comment by nivida** [comment]
I'm closing this issue because it does work after a restart and is definitely not an issue of ``geth-dev-assistant``.
